(tool-bar-mode nil)
(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)
(when (>= emacs-major-version 24)
    (require 'package)
    (package-initialize)
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
    )
(require 'ack)
(require 'jenkins-watch)
(require 'cider)
(require 'ido)
(ido-mode t)
(osx-clipboard-mode +1)
(rainbow-delimiters-mode t)
(add-hook 'after-init-hook 'global-company-mode)

